# Generated by Django 3.1 on 2021-03-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210227_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
