# Generated by Django 3.1 on 2021-02-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=210)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField(max_length=48)),
                ('image', models.ImageField(null=True, upload_to='product-images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product-thumbnails')),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
